# Generated by Django 3.1.1 on 2020-12-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefeeditem',
            name='campaign_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/campagns/'),
        ),
    ]
