# Generated by Django 3.1.3 on 2020-11-30 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('care_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationhistory',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_api.profilefeeditem'),
        ),
    ]
