# Generated by Django 3.1.3 on 2020-12-01 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_api', '0002_auto_20201130_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationhistory',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
